### ISSUE TITLE
Is Koken actually licensed as Open Source?

### ISSUE THREAD

**Issue by ghost** [ibaaj/awesome-OpenSourcePhotography#2]
Not to put a blight on your efforts, I think you've done an awesome (pun intended) job.

Last time I checked (less than a minute ago, when posting this), Koken isn't licensed as Open Source (http://koken.me/eula.html), it is Free. I do like Koken, just thought I'd bring it up, in case you wanted to be strict on a projects license.

Anyway, keep up the great work.

**Comment by ibaaj** [comment]
[removed](https://github.com/ibaaj/awesome-OpenSourcePhotography/commit/45a436323975a23ff865edcf6232771daa823478) 
thanks for you help!

**Comment by ghost** [comment]
Koken is pretty good software, I don't see any reason not to have it on the list, but I would suggest mentioning that it isn't Open Source, that way people can make an informed choice.

Thanks for looking into it though.

**Comment by ibaaj** [comment]
sorry for my short answer - I was very busy yesterday.

The problem is more about relevance : my repo title suggests _open source software_, or Koken isn't one. Do you think we have to make an exception ?

**Comment by ghost** [comment]
It's all good, I'm lucky enough to be in a position where I don't have to work a job, hardest part of my day is cutting wood, and feeding the goats and sheep, lol.

Personally, I wouldn't list as it's not licensed as FOSS, I just didn't want to come across as pushy, it's your repo after all. I wasn't sure if you were aware of Koken's licensing. I do like the project, it's good at what it does. I looked into modifying it for my own needs, but discovered that other than reverse engineering all their minified code, their source isn't available.

**Comment by ibaaj** [comment]
Hope the goats and sheep eat well :) 

I was aware about Koken's licensing. I added it to the list because as you say it's a good program - I tried it. As the list wasn't very popular, I thought that I could put it - it's at least free.

You weren't pushy ;)

**Comment by ghost** [comment]
They eat better than we do at times, lol.

I discovered the repo through /r/opensource on Reddit. From there, I shared it in each of the Communities, where Pat picked up on it in the Facebook Group. Feel free to go through the groups to look for more things to add too your list. If I think of anything, I'll be sure to do a PR as well.
