### ISSUE TITLE
No mention of PIXLS.US?

### ISSUE THREAD

**Issue by patdavid** [ibaaj/awesome-OpenSourcePhotography#3]
If you haven't seen it already, this is a Free Software community used by many of these projects as well. Have a look if you get a chance! :)
https://pixls.us

**Comment by ghost** [comment]
This site deserves to be added. Pat David does a hell of a lot for the Open Source community, and provides valuable and proper information.

**Comment by ibaaj** [comment]
[added](https://github.com/ibaaj/awesome-OpenSourcePhotography/commit/45a436323975a23ff865edcf6232771daa823478) !
