### ISSUE TITLE
Suggestion: Category for Resource websites?

### ISSUE THREAD

**Issue by ghost** [ibaaj/awesome-OpenSourcePhotography#5]
I was going to do a PR to add https://www.unsplash.com/ 

But not sure which existing category to add it too, or if maybe have a new category for such resources.

**Comment by ibaaj** [comment]
Hello and again thanks you for contributing ! 
- Hired Peter 
- Peter created the category called ["Resources"](https://github.com/ibaaj/awesome-OpenSourcePhotography#resources) and added to it unsplash.com without "www"
- Fired Peter

[more informations about Peter](https://www.quora.com/Who-is-Peter-the-guy-allegedly-fired-by-Medium-according-to-their-iOS-App-changelog)

**Comment by ghost** [comment]
lol, awesome, I've found unsplash to be quite handy. Even posted some photo's (https://unsplash.com/@devel) there myself. I really need to get out and do more Photography, lol.
